//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPV_HISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NPV_HISTORY()
        {
            this.NPV_HISTORY_CASHFLOWS = new HashSet<NPV_HISTORY_CASHFLOWS>();
        }
    
        public System.Guid ID { get; set; }
        public decimal INITIAL_VALUE { get; set; }
        public decimal LOWER_BOUND_DISCOUNT_RATE { get; set; }
        public decimal UPPER_BOUND_DISCOUNT_RATE { get; set; }
        public decimal INCREMENT { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NPV_HISTORY_CASHFLOWS> NPV_HISTORY_CASHFLOWS { get; set; }
    }
}
