//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPV_HISTORY_CASHFLOWS
    {
        public System.Guid ID { get; set; }
        public System.Guid NPV_HISTORY_ID { get; set; }
        public decimal CASH_FLOW { get; set; }
        public int ORDER { get; set; }
    
        public virtual NPV_HISTORY NPV_HISTORY { get; set; }
    }
}
